# Generated by Django 5.1.6 on 2025-03-02 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams_app', '0002_remove_enrollment_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='section',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
